### ISSUE TITLE
/entrypoint.sh: line 95: tr: not found

### ISSUE THREAD

**Issue by StephenGravitt** [up9cloud/action-rsync#7]
Hello,

Tried out your action today, looks pretty slick. Unfortunately it did not work for me. I got the error:
/entrypoint.sh: line 95: tr: not found

Any ideas on how to get this up and running quickly?

I was thinking of force-installing tr OR referencing /usr/bin/tr which is the common ubuntu path.

I can submit a PR but I might need some guidance on how to test an update to confirm it is fixed.

Let me how I can help, thanks!

**Comment by up9cloud** [comment]
It should not happen, this action is based on alpine linux container (with `tr` command).

Could you provide your workflow config yaml file?

**Comment by StephenGravitt** [comment]
Hi there,

You're correct, nothing wrong with this code. I did find the issue and it
had to do with GITHUB_ENV variables that were either too large or
improperly stored causing some odd issues.

Sorry for the false alarm here.
